language: erlang
otp_release:
- 17.4
env:
- BUILD_DIR=$HOME/rabbitmq-public-umbrella RABBIT_TAG=v3_5_1
- BUILD_VERSION=v3.5.x
before_install:
- "$TRAVIS_BUILD_DIR/travis-umbrella-setup.sh"
install:
- sudo apt-get update -qq
- sudo apt-get install -qq -y xsltproc
script: cd $BUILD_DIR/epgsql-wrapper && make test
after_script:
- rm -rf $BUILD_DIR/epgsql-wrapper
before_deploy:
- cd $BUILD_DIR/epgsql-wrapper
- VERSION=$BUILD_VERSION make
cache:
  apt: true
  directories:
  - "$BUILD_DIR"
deploy:
  provider: releases
  api_key:
    secure: AD5omb7JwF4uC2c0fhKEMvK3GIEKSQor8YquuWLQQa568QEyBPVJcNGl6VJMHS+NIiA/uVNQ4wS6lut/CxK2thtXRphOB73Y1dOgv3nkRTRwWswOccrzSpfhsRoxA+EiA2K9nEGHrUznXjDS1ZYM0LiNXZaj8mlfNwgBiczj06Q=
  file: $BUILD_DIR/epgsql-wrapper/dist/epgsql-wrapper-${TRAVIS_TAG}.ez
  on:
    tags: true
    repo: gmr/epgsql-wrapper
